[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Handle Next.js server-side rendering and API routes
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200
